import type {
  WorkflowSummary,
  IssueSummary,
  ChangeRequestSummary,
  MonitoringSettingsResponse,
  ListWorkflowsResponse,
  IssueDetailsResponse,
  ChangeRequestDetailsResponse,
} from "../apps/web/src/generated/contracts";

export const timestamp = "2026-09-28T10:00:00Z";
const identity = {
  sourceId: "github",
  sourceName: "GitHub",
  sourceAbbreviation: "GH",
  repositoryId: "api",
  repositoryOwner: "acme",
  repositoryName: "api",
};
export const workflows: WorkflowSummary[] = [
  {
    name: "Build and test",
    repository: "api",
    outcome: "failure",
    lifecycle: "completed",
  },
  {
    name: "Deploy preview",
    repository: "web",
    outcome: "unknown",
    lifecycle: "running",
  },
  {
    name: "Release",
    repository: "infra",
    outcome: "success",
    lifecycle: "completed",
  },
].map((item, index) => ({
  ...identity,
  repositoryId: item.repository,
  repositoryName: item.repository,
  id: `workflow-${index}`,
  name: item.name,
  path: ".github/workflows/build.yml",
  state: "active",
  webUrl: "https://github.com/acme/api/actions",
  runs: [
    {
      id: `run-${index}`,
      runNumber: 128 + index,
      attempt: 1,
      title: "Improve deployment reliability",
      lifecycle: item.lifecycle as "completed" | "running",
      outcome: item.outcome as "failure" | "success" | "unknown",
      branch: "main",
      commitSha: "abc123456789",
      actor: "alice",
      trigger: "push",
      createdAt: timestamp,
      startedAt: timestamp,
      updatedAt: "2026-09-28T10:02:00Z",
      webUrl: "https://github.com/acme/api/actions/runs/128",
    },
  ],
}));

const build = workflows[0];
const latestRun = build.runs[0];
build.runs.push(
  {
    ...latestRun,
    id: "run-build-127",
    runNumber: 127,
    title: "Add deployment health checks",
    lifecycle: "completed",
    outcome: "success",
    branch: "feature/health-checks",
    actor: "bob",
    createdAt: "2026-09-28T09:58:00Z",
    startedAt: "2026-09-28T09:58:00Z",
    updatedAt: "2026-09-28T10:01:00Z",
    webUrl: "https://github.com/acme/api/actions/runs/127",
  },
  {
    ...latestRun,
    id: "run-build-126",
    runNumber: 126,
    title: "Cache dependencies between builds",
    lifecycle: "completed",
    outcome: "success",
    commitSha: "def456789abc",
    createdAt: "2026-09-28T09:35:00Z",
    startedAt: "2026-09-28T09:35:00Z",
    updatedAt: "2026-09-28T09:38:00Z",
    webUrl: "https://github.com/acme/api/actions/runs/126",
  },
  {
    ...latestRun,
    id: "run-build-125",
    runNumber: 125,
    title: "Update integration test fixtures",
    lifecycle: "completed",
    outcome: "success",
    actor: "bob",
    commitSha: "fed987654321",
    createdAt: "2026-09-28T09:10:00Z",
    startedAt: "2026-09-28T09:10:00Z",
    updatedAt: "2026-09-28T09:14:00Z",
    webUrl: "https://github.com/acme/api/actions/runs/125",
  },
);
workflows.splice(
  1,
  0,
  {
    ...build,
    id: "workflow-api-lint",
    name: "Lint and typecheck",
    path: ".github/workflows/lint.yml",
    runs: [
      {
        ...latestRun,
        id: "run-lint-84",
        runNumber: 84,
        title: "Tighten API response types",
        lifecycle: "completed",
        outcome: "success",
        commitSha: "bcd234567890",
        webUrl: "https://github.com/acme/api/actions/runs/84",
      },
    ],
  },
  {
    ...build,
    id: "workflow-api-container",
    name: "Publish container",
    path: ".github/workflows/container.yml",
    runs: [
      {
        ...latestRun,
        id: "run-container-63",
        runNumber: 63,
        title: "Build October release candidate",
        lifecycle: "running",
        outcome: "unknown",
        branch: "release/october",
        webUrl: "https://github.com/acme/api/actions/runs/63",
      },
    ],
  },
);
export const inventory: ListWorkflowsResponse = {
  selectedRepositoryCount: 3,
  workflows,
  lastAttemptedAt: Date.parse(timestamp) / 1000,
  lastSuccessfulAt: Date.parse(timestamp) / 1000,
  stale: false,
  syncError: null,
};
export const issues: IssueSummary[] = [
  {
    ...identity,
    id: "issue-1",
    number: 42,
    title: "Retry failed deployments",
    author: "alice",
    state: "open",
    labels: ["bug", "priority"],
    assignees: ["bob"],
    commentCount: 1,
    createdAt: timestamp,
    updatedAt: timestamp,
    webUrl: "https://github.com/acme/api/issues/42",
  },
  {
    ...identity,
    id: "issue-2",
    number: 43,
    title: "Document release process",
    author: "bob",
    state: "open",
    labels: ["documentation"],
    assignees: [],
    commentCount: 0,
    createdAt: timestamp,
    updatedAt: timestamp,
    webUrl: "https://github.com/acme/api/issues/43",
  },
];
export const pullRequests: ChangeRequestSummary[] = [
  {
    ...identity,
    id: "pr-1",
    number: 17,
    title: "Improve build checks",
    author: "alice",
    sourceBranch: "feature/build-checks",
    targetBranch: "main",
    state: "open",
    draft: false,
    reviewStatus: "changesRequested",
    checkStatus: "failing",
    mergeStatus: "ready",
    createdAt: timestamp,
    updatedAt: timestamp,
    webUrl: "https://github.com/acme/api/pull/17",
  },
  {
    ...identity,
    id: "pr-2",
    number: 18,
    title: "Add deployment metrics",
    author: "bob",
    sourceBranch: "feature/metrics",
    targetBranch: "main",
    state: "open",
    draft: false,
    reviewStatus: "approved",
    checkStatus: "passed",
    mergeStatus: "ready",
    createdAt: timestamp,
    updatedAt: timestamp,
    webUrl: "https://github.com/acme/api/pull/18",
  },
];
export const issueDetails: IssueDetailsResponse = {
  title: issues[0].title,
  state: "open",
  labels: issues[0].labels,
  assignees: ["bob"],
  commentCount: 1,
  updatedAt: timestamp,
  milestone: "October release",
  body: "## Deployment retries\n\nRetry transient failures before alerting the on-call engineer.",
  comments: [
    {
      id: "comment-1",
      author: "bob",
      body: "Investigating the timeout in the deploy job.",
      createdAt: timestamp,
      updatedAt: timestamp,
    },
  ],
};
export const pullRequestDetails: ChangeRequestDetailsResponse = {
  body: "## Build checks\n\nAdd integration checks before publishing a release.",
  labels: ["ci"],
  reviews: [
    { reviewer: "bob", status: "changesRequested", submittedAt: timestamp },
  ],
  checks: [
    {
      name: "Build and test",
      status: "failing",
      webUrl: null,
      workflowRunId: "run-0",
    },
  ],
  latestCommit: {
    sha: "abc123456789",
    title: "Add integration checks",
    author: "alice",
    committedAt: timestamp,
  },
};
export const settings: MonitoringSettingsResponse = {
  pullRequestsEnabled: true,
  issuesEnabled: true,
  onlyMyWork: false,
  synchronizationIntervalSeconds: 60,
  recentRunsPerWorkflow: 10,
  notifications: {
    workflowFailures: true,
    pullRequestOpened: true,
    pullRequestReviewRequested: true,
    pullRequestChangesRequested: true,
    pullRequestMerged: true,
    pullRequestClosed: true,
    issueOpened: true,
    issueAssigned: true,
    issueReopened: true,
    issueClosed: true,
  },
};
