[package]
name = "ciwatcher-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
async-trait.workspace = true
ciwatcher-core.workspace = true
keyring = "4.2.0"
tauri.workspace = true
tauri-plugin-notification.workspace = true
tokio.workspace = true

[lints]
workspace = true
